# Generated by Django 3.2 on 2021-04-23 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_no', models.AutoField(primary_key=True, serialize=False)),
                ('user_password', models.CharField(max_length=100)),
                ('user_email', models.CharField(max_length=50)),
                ('user_nickname', models.CharField(max_length=20)),
                ('user_location', models.CharField(max_length=20)),
                ('user_gender', models.CharField(max_length=20)),
                ('user_birthdate', models.DateField(blank=True, null=True)),
                ('user_createat', models.DateField(blank=True, null=True)),
                ('user_caution', models.IntegerField(blank=True, null=True)),
                ('user_sellcount', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
